In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,OrdinalEncoder, PolynomialFeatures
from category_encoders import TargetEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
np.random.seed(42)

In [3]:
n_rows  = 1000
data = {
    'color':np.random.choice(['red','blue','green'],n_rows),
    'size': np.random.choice(['small','medium','large'],n_rows),
    'material': np.random.choice(['plastic','metal','wood'],n_rows),
    'price': np.random.randint(10,500,n_rows)
}

df = pd.DataFrame(data)

In [4]:
df.head()

,color,size,material,price
0,green,large,metal,423
1,red,large,plastic,351
2,green,large,plastic,229
3,green,large,wood,400
4,red,small,plastic,172


In [5]:
x = df.drop(columns = 'price')
y = df.price

In [6]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size = 0.2,random_state=42)

In [7]:
label_encoder = LabelEncoder()
# updated_xtrain = label_encoder.fit_transform(xtrain)
'''
ValueError: y should be a 1d array, got an array of shape (200, 3) instead.
'''

'\nValueError: y should be a 1d array, got an array of shape (200, 3) instead.\n'

In [8]:
label_encoder.fit_transform(xtrain['color'])


array([1, 0, 0, 2, 1, 1, 2, 1, 0, 1, 0, 1, 0, 0, 0, 2, 0, 1, 1, 2, 0, 1,
       2, 0, 2, 1, 1, 1, 1, 2, 2, 0, 0, 2, 0, 1, 2, 2, 2, 1, 1, 0, 2, 1,
       2, 0, 1, 1, 2, 2, 0, 1, 0, 0, 1, 1, 1, 1, 0, 2, 2, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2, 0, 2, 0, 1, 0, 2, 2, 2, 2,
       1, 1, 2, 2, 0, 1, 0, 2, 1, 0, 0, 1, 0, 0, 0, 2, 1, 0, 1, 2, 1, 2,
       2, 1, 1, 1, 1, 0, 1, 1, 2, 1, 0, 2, 2, 2, 2, 2, 1, 0, 0, 0, 2, 1,
       2, 0, 1, 0, 1, 0, 2, 1, 0, 0, 1, 2, 2, 1, 2, 2, 2, 2, 1, 2, 0, 2,
       2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 0, 1, 1, 2, 2, 0, 0, 0, 1, 0, 1, 1,
       2, 0, 1, 1, 1, 1, 2, 2, 2, 0, 0, 2, 0, 2, 2, 1, 1, 2, 1, 1, 1, 0,
       0, 1, 2, 0, 0, 0, 0, 2, 0, 2, 2, 1, 1, 1, 2, 0, 1, 0, 0, 0, 2, 1,
       0, 0, 0, 1, 0, 1, 2, 2, 0, 2, 1, 0, 2, 0, 2, 2, 0, 0, 1, 2, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 2, 1, 2, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 2, 0, 2, 0, 0, 2, 1, 2, 2, 2, 0, 1, 2, 1, 0, 2, 1, 0, 1, 2,
       1, 1, 2, 2, 2, 2, 2, 1, 0, 2, 0, 0, 1, 2, 2,

In [9]:
# label_encoder.transform(xtest)
'''
ValueError: y should be a 1d array, got an array of shape (800, 3) instead.
'''

'\nValueError: y should be a 1d array, got an array of shape (800, 3) instead.\n'

In [10]:
# new_input -> for unseen data
new_input = ['red','red']
label_encoder.transform(new_input)


array([2, 2])

* transform() method is madantory before we going to predict for unseen data

* LabelEncoder will store the values in the form of dict(key value pairs)
* labelEncoder will not handle errors

In [11]:
#OneHotEncoder -> Method 1
encoder = OneHotEncoder() 
# values = encoder.fit_transform(xtrain['color'])
'''
ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. 
Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.

'''
values = encoder.fit_transform(xtrain)

#toarray()
# values = values.toarray()
values


<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2400 stored elements and shape (800, 9)>

In [12]:
#OneHotEncoder -> Method 2
encoder = OneHotEncoder(sparse_output=False) # BY defalult the sparse_output=True
# values = encoder.fit_transform(xtrain['color'])
'''
ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. 
Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.

'''
values = encoder.fit_transform(xtrain)
values


array([[0., 1., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       ...,
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.]], shape=(800, 9))

In [13]:
columns = encoder.get_feature_names_out() 
''' will get all the column names that are created by the OneHotEncoder,
for all the unique values with colname in ascending order '''

' will get all the column names that are created by the OneHotEncoder,\nfor all the unique values with colname in ascending order '

In [14]:
# pd.DataFrame(values,columns = columns)

In [15]:
# encoder.transform(xtest['color'])
'''
ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead.
Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.

'''
# encoder.transform(xtest[ ['color','size']])
'''
ValueError: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- material
'''
# Valid Syntax is

encoder.transform(xtest)


array([[0., 0., 1., ..., 1., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 1., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.]], shape=(200, 9))

In [16]:
# new_input = [['red','large'],['blue','small']] 
# encoder.transform(new_input)

'''
ValueError: X has 2 features, but OneHotEncoder is expecting 3 features as input.
'''

'\nValueError: X has 2 features, but OneHotEncoder is expecting 3 features as input.\n'

In [17]:
# new_input = [['red1','large','plastic'],['blue','small','wood']] 
# encoder.transform(new_input)
'''
ValueError: Found unknown categories ['red1'] in column 0 during transform
'''

"\nValueError: Found unknown categories ['red1'] in column 0 during transform\n"

In [18]:
encoder = OneHotEncoder(sparse_output=False,handle_unknown='ignore') # by default handle_unknown = 'error'
updated_xtrain = encoder.fit_transform(xtrain)
new_input = [['red1','large1','plastic'],['blue','small','wood']] 
encoder.transform(new_input)

c:\Users\chara\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1.]])

In [19]:
encoder.get_feature_names_out()

array(['color_blue', 'color_green', 'color_red', 'size_large',
       'size_medium', 'size_small', 'material_metal', 'material_plastic',
       'material_wood'], dtype=object)

## Ordinal Encoder

In [20]:
ordinal_encoder = OrdinalEncoder()
updated_xtrain = ordinal_encoder.fit_transform(xtrain)
updated_xtrain

array([[1., 2., 2.],
       [0., 1., 0.],
       [0., 2., 2.],
       ...,
       [0., 0., 1.],
       [0., 2., 1.],
       [1., 2., 1.]], shape=(800, 3))

In [21]:
ordinal_encoder.get_feature_names_out()

array(['color', 'size', 'material'], dtype=object)

In [22]:
'''
updated_xtrain = ordinal_encoder.fit_transform(xtrain['color'])

ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead.
Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.
'''


"\nupdated_xtrain = ordinal_encoder.fit_transform(xtrain['color'])\n\nValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead.\nPass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.\n"

In [23]:
updated_xtest = ordinal_encoder.transform(xtest)
updated_xtest

array([[2., 2., 0.],
       [2., 2., 0.],
       [0., 2., 0.],
       [1., 2., 1.],
       [0., 1., 0.],
       [2., 0., 1.],
       [1., 0., 1.],
       [2., 2., 1.],
       [2., 0., 0.],
       [0., 2., 0.],
       [0., 2., 0.],
       [0., 0., 0.],
       [2., 0., 1.],
       [0., 1., 2.],
       [1., 2., 0.],
       [2., 0., 0.],
       [1., 1., 2.],
       [2., 0., 1.],
       [2., 0., 2.],
       [0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.],
       [1., 2., 1.],
       [0., 1., 1.],
       [2., 1., 1.],
       [0., 1., 2.],
       [1., 0., 0.],
       [2., 2., 0.],
       [0., 2., 0.],
       [1., 1., 1.],
       [2., 1., 0.],
       [2., 0., 2.],
       [0., 2., 0.],
       [1., 2., 0.],
       [0., 1., 0.],
       [0., 0., 2.],
       [2., 2., 2.],
       [2., 1., 1.],
       [2., 1., 0.],
       [1., 0., 0.],
       [2., 2., 2.],
       [2., 1., 2.],
       [1., 0., 0.],
       [2., 0., 1.],
       [0., 0., 1.],
       [1., 0., 2.],
       [1., 0., 2.],
       [1., 2

In [24]:
'''
updated_xtest = ordinal_encoder.transform(xtest['color'])

ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. 
Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.
'''

"\nupdated_xtest = ordinal_encoder.transform(xtest['color'])\n\nValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. \nPass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.\n"

In [25]:
# # unknown values
# new_input = [['red1','large','plastic'],['blue','small','wood']]
# ordinal_encoder.transform(new_input) #ValueError: Found unknown categories ['red1'] in column 0 during transform

In [26]:
# handling unknown values
ordinal_encoder = OrdinalEncoder(handle_unknown='use_encoded_value',unknown_value=-1)
updated_xtrain = ordinal_encoder.fit_transform(xtrain)
updated_xtest = ordinal_encoder.transform(xtest)

# new_data = [['red1','large','plastic'],['blue','small','wood']] # this will give warning because we have not passed the feature names
new_data = pd.DataFrame(data = [['red1','large','plastic'],['blue','small','wood']], columns=['color','size','material'] )  # this will not give warning
updated_new_data = ordinal_encoder.transform(new_data)
updated_new_data


array([[-1.,  0.,  1.],
       [ 0.,  2.,  2.]])

In [27]:
# With order
'''
ordinal_encoder = OrdinalEncoder(categories=[['green','blue','red']],handle_unknown='use_encoded_value',unknown_value=-1) #ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,).
ordinal_encoder.fit_transform(xtrain)

'''
''' # bcz xtrain is having three columns and categories have only 1 ctaegory ordeer so shape mismatch error 
the orders in the ctegories and in the fit trasnform should match otherwise it will give value error
'''

' # bcz xtrain is having three columns and categories have only 1 ctaegory ordeer so shape mismatch error \nthe orders in the ctegories and in the fit trasnform should match otherwise it will give value error\n'

In [28]:
# ordinal_encoder = OrdinalEncoder(categories=[['small','medium','large'],['green1','blue','red'],['plastic','metal','wood']]) #ValueError: Found unknown categories ['red', 'green', 'blue'] in column 0 during fit
# ordinal_encoder.fit_transform(xtrain)

In [29]:
# ordinal_encoder = OrdinalEncoder(categories=[['small','medium','large'],['green1','blue','red'],['plastic','metal','wood']],handle_unknown='use_encoded_value') #TypeError: unknown_value should be an integer or np.nan when handle_unknown is 'use_encoded_value', got None.
# ordinal_encoder.fit_transform(xtrain)

In [30]:
ordinal_encoder = OrdinalEncoder(categories=[['green','blue','red'],['small','medium','large'],['plastic','wood','metal']],handle_unknown='use_encoded_value',unknown_value=-1)
ordinal_encoder.fit_transform(xtrain)
ordinal_encoder.transform(xtest)

array([[2., 0., 2.],
       [2., 0., 2.],
       [1., 0., 2.],
       [0., 0., 0.],
       [1., 1., 2.],
       [2., 2., 0.],
       [0., 2., 0.],
       [2., 0., 0.],
       [2., 2., 2.],
       [1., 0., 2.],
       [1., 0., 2.],
       [1., 2., 2.],
       [2., 2., 0.],
       [1., 1., 1.],
       [0., 0., 2.],
       [2., 2., 2.],
       [0., 1., 1.],
       [2., 2., 0.],
       [2., 2., 1.],
       [1., 2., 2.],
       [0., 2., 2.],
       [0., 1., 2.],
       [0., 0., 0.],
       [1., 1., 0.],
       [2., 1., 0.],
       [1., 1., 1.],
       [0., 2., 2.],
       [2., 0., 2.],
       [1., 0., 2.],
       [0., 1., 0.],
       [2., 1., 2.],
       [2., 2., 1.],
       [1., 0., 2.],
       [0., 0., 2.],
       [1., 1., 2.],
       [1., 2., 1.],
       [2., 0., 1.],
       [2., 1., 0.],
       [2., 1., 2.],
       [0., 2., 2.],
       [2., 0., 1.],
       [2., 1., 1.],
       [0., 2., 2.],
       [2., 2., 0.],
       [1., 2., 0.],
       [0., 2., 1.],
       [0., 2., 1.],
       [0., 0

## Target Encoders!

In [31]:
target_encoder = TargetEncoder(cols=['color'])  # we use cols parameter when we have mixed datatype columns
target_encoder.fit_transform(xtrain,ytrain) # it will not remove remaing columns it only applies target encoder to only mentoioned column

,color,size,material
29,253.164751,small,wood
535,256.408397,medium,metal
695,256.408397,small,wood
557,263.678700,small,plastic
836,253.164751,large,plastic
...,...,...,...
106,263.678700,large,plastic
270,263.678700,small,plastic
860,256.408397,large,plastic
435,256.408397,small,plastic


In [32]:
target_encoder = TargetEncoder(cols=['color'],handle_unknown='value') 
target_encoder.fit_transform(xtrain,ytrain)

,color,size,material
29,253.164751,small,wood
535,256.408397,medium,metal
695,256.408397,small,wood
557,263.678700,small,plastic
836,253.164751,large,plastic
...,...,...,...
106,263.678700,large,plastic
270,263.678700,small,plastic
860,256.408397,large,plastic
435,256.408397,small,plastic


In [33]:
target_encoder.transform(xtest)

,color,size,material
521,263.678700,small,metal
737,263.678700,small,metal
740,256.408397,small,metal
660,253.164751,small,plastic
411,256.408397,medium,metal
...,...,...,...
408,253.164751,small,metal
332,263.678700,large,metal
208,263.678700,small,metal
613,253.164751,small,plastic


In [37]:
# new_input = [['red','small','wood1']] #KeyError: 'color'
# target_encoder.transform(new_input)

In [38]:
new_input = pd.DataFrame({"color" : ['red1'], 'size' : ['small'], 'material': ['wood1'] })
target_encoder.transform(new_input)

,color,size,material
0,257.8675,small,wood1


In [39]:
target_encoder = TargetEncoder(handle_unknown='value') 
target_encoder.fit_transform(xtrain,ytrain)

,color,size,material
29,253.164751,263.081784,245.481013
535,256.408397,254.923077,264.018248
695,256.408397,263.081784,245.481013
557,263.678700,263.081784,262.193772
836,253.164751,255.546512,262.193772
...,...,...,...
106,263.678700,255.546512,262.193772
270,263.678700,263.081784,262.193772
860,256.408397,255.546512,262.193772
435,256.408397,263.081784,262.193772


In [40]:
# new_input = [['red','small','wood1']] 
# target_encoder.transform(new_input)
new_input = pd.DataFrame({"color" : ['red1'], 'size' : ['small'], 'material': ['wood1'] })
target_encoder.transform(new_input)

,color,size,material
0,257.8675,263.081784,257.8675
