In [22]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split

In [23]:
x = pd.DataFrame({
    'col_1': [1.2, 2.5, None, 4.1, None, 6.3, None, 8.4, 9.1, 10.2],
    'col_2': [10, None, 30, 40, 50, None, 70, 80, 90, 100],
    'col_3': ['A', 'B', 'A', None, 'C', 'A', 'C', 'A', None, 'B'],
    'col_4': ['AA', 'BB', 'AA', np.nan, 'CC', 'AA', np.nan, 'AA', np.nan, 'BB']

})

In [28]:
x

,col_1,col_2,col_3,col_4
0,1.2,10.0,A,AA
1,2.5,NaN,B,BB
2,NaN,30.0,A,AA
3,4.1,40.0,None,NaN
4,NaN,50.0,C,CC
5,6.3,NaN,A,AA
6,NaN,70.0,C,NaN
7,8.4,80.0,A,AA
8,9.1,90.0,None,NaN
9,10.2,100.0,B,BB


In [24]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   col_1   7 non-null      float64
 1   col_2   8 non-null      float64
 2   col_3   8 non-null      object 
 3   col_4   7 non-null      object 
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes


In [ ]:
imputer =SimpleImputer(strategy='constant',fill_value='unknow') # it will work for both 
imputer.fit_transform(x)

array([[1.2, 10.0, 'A', 'AA'],
       [2.5, 'unknow', 'B', 'BB'],
       ['unknow', 30.0, 'A', 'AA'],
       [4.1, 40.0, None, 'unknow'],
       ['unknow', 50.0, 'C', 'CC'],
       [6.3, 'unknow', 'A', 'AA'],
       ['unknow', 70.0, 'C', 'unknow'],
       [8.4, 80.0, 'A', 'AA'],
       [9.1, 90.0, None, 'unknow'],
       [10.2, 100.0, 'B', 'BB']], dtype=object)

In [ ]:
imputer =SimpleImputer(strategy='constant',fill_value='unknow') 
imputer.fit_transform(x[['col_3','col_4']])

array([['A', 'AA'],
       ['B', 'BB'],
       ['A', 'AA'],
       [None, 'unknow'],
       ['C', 'CC'],
       ['A', 'AA'],
       ['C', 'unknow'],
       ['A', 'AA'],
       [None, 'unknow'],
       ['B', 'BB']], dtype=object)

In [30]:
imputer =SimpleImputer(strategy='mean') 
imputer.fit_transform(x[['col_1','col_2']])

array([[  1.2       ,  10.        ],
       [  2.5       ,  58.75      ],
       [  5.97142857,  30.        ],
       [  4.1       ,  40.        ],
       [  5.97142857,  50.        ],
       [  6.3       ,  58.75      ],
       [  5.97142857,  70.        ],
       [  8.4       ,  80.        ],
       [  9.1       ,  90.        ],
       [ 10.2       , 100.        ]])

In [33]:
imputer =SimpleImputer(strategy='median') 
imputer.fit_transform(x[['col_1','col_2']])

array([[  1.2,  10. ],
       [  2.5,  60. ],
       [  6.3,  30. ],
       [  4.1,  40. ],
       [  6.3,  50. ],
       [  6.3,  60. ],
       [  6.3,  70. ],
       [  8.4,  80. ],
       [  9.1,  90. ],
       [ 10.2, 100. ]])